### ISSUE TITLE
How to reverse toggle so ON is a right toggle action

### ISSUE THREAD

**Issue by stevenjohn** [miladd3/clean-switch#1]
Hi there,

Congratulations on such a cool library, we're using it inside our task.io desktop admin area - many thanks 👍 

My question is - any reason for making the on position to the left? Most UX says that ON = to the right.

I'd like to reverse it so the right position is ON, is there any easy way to do this?

Kind regards, Steve.

**Comment by miladd3** [comment]
Hi thanks for using the library and creating this issue

I researched and found out you are right about the direction of the toggle so I will change it in an update soon 
and set the default to the right side

**Comment by miladd3** [comment]
@stevenjohn 
Project updated and now the default direction for ON is right side
